# Generated by Django 2.2.7 on 2019-11-19 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('adress', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('picture', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='my_app.Customer')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='my_app.Product')),
            ],
        ),
    ]
